name: run newsapp.py

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute scrape_aljazeera 
        run: python scripts/scrape_aljazeera.py
      
      - name: execute scrape_middleeasteye 
        run: python scripts/scrape_middleeasteye.py

      - name: Commit and push DB (if changed)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update DB after scraping" || echo "No changes to commit"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}